### ISSUE TITLE
Subraya items header

### ISSUE THREAD

**Issue by nomad4real** [nomad4real/sarrs#2]
Programaticamente cambiar a active segun pagina vista:
![image](https://user-images.githubusercontent.com/9743103/34679308-532efbda-f474-11e7-80ba-23070ffeabac.png)

Para que corresponda a la pagina en vista
![image](https://user-images.githubusercontent.com/9743103/34679331-62579018-f474-11e7-8355-ab12849f3e86.png)

**Comment by Alpeh-Jav** [comment]
What do you means  with "active"?

**Comment by nomad4real** [comment]
Active es una clase de boostrap.
![image](https://user-images.githubusercontent.com/9743103/34680914-17a7ac60-f479-11e7-9699-66ae3c59055e.png)

Pero eliminare el requerimiento ya que el header lo saque del Layout y lo puse en cada item

**Comment by Alpeh-Jav** [comment]
y cuál era el problema del header? goddammit best engineer in the galaxy

**Comment by nomad4real** [comment]
No, como el header era una plantilla era igual para todas, pero ahora se cambio para que fuera individual y asignar el activa para cada header correspondiente.

**Comment by Alpeh-Jav** [comment]
Ya. Entonces. El header estaba en el layaut (padre), el cual estaba configurado para que subrayara algo específico, entonces cada vista (página) tenía subrayado lo mismo y no lo que realmente le correspondía. Gotcha.
