### ISSUE TITLE
Las imagenes no se muestran en las diferentes paginas

### ISSUE THREAD

**Issue by nomad4real** [nomad4real/sarrs#3]
Se deberian mostrar las imagenes en cada pagina, actualmente solo funciona para la principal
![image](https://user-images.githubusercontent.com/9743103/34682647-51a48032-f47e-11e7-8b69-8f4317089444.png)

Alguna otra pagina:
![image](https://user-images.githubusercontent.com/9743103/34682668-5bb3cb96-f47e-11e7-9b78-3f1d2c3929f0.png)

**Comment by Alpeh-Jav** [comment]
ok. ya sé cuál es el problema, pero de paso mataré dos pájaros de un tiro.

**Comment by Alpeh-Jav** [comment]
ready
