### ISSUE TITLE
OPCIONAL: Investigar Funcionalidad boton Get Quote

### ISSUE THREAD

**Issue by nomad4real** [nomad4real/sarrs#4]
![image](https://user-images.githubusercontent.com/9743103/34682932-43c82c92-f47f-11e7-991c-0c777b59cba6.png)

Aparece un mensaje y es para enviar. tla vez ver cvomo implementar. PERO NO ES NECESARIO PARA ELK PROYECTO

**Comment by Alpeh-Jav** [comment]
Escribe bien, mierda. xDDDDDD

**Comment by Alpeh-Jav** [comment]
En cuál de los 39 html está?

**Comment by nomad4real** [comment]
mejor dirigimos ese boton a la planilla contactos. ademas

**Comment by Alpeh-Jav** [comment]
Implementado en convenio.
