### ISSUE TITLE
Contactanos.cshtml no muestra Google Map

### ISSUE THREAD

**Issue by Alpeh-Jav** [nomad4real/sarrs#5]
No se muestra Google Map en Contactanos.cshtml 
![image](https://user-images.githubusercontent.com/19765542/34758294-13ba390a-f5b5-11e7-8964-9ac17a71556a.png)
Mientras que en contacts-us.html de la plantilla sí lo hace
![image](https://user-images.githubusercontent.com/19765542/34758320-362c2110-f5b5-11e7-9fdf-e21ab62cb96f.png)
Revisé por encima el código html y no se ven diferencias importante.

**Comment by Alpeh-Jav** [comment]
Está todo muy raro. El servidor rompe el javascript, mira:

Página html lanzada directa desde el explorador de windows (**mapa funciona**)
![image](https://user-images.githubusercontent.com/19765542/34802410-46f4da2c-f64c-11e7-97dc-0ab5eccd9e49.png)
Páina html lanzada desde el visual y mostrada desde localhost (**mapa no funciona**)
![image](https://user-images.githubusercontent.com/19765542/34802431-5c13f348-f64c-11e7-94a2-473ead408548.png)

Presentan diferencias en el "source", específicamente en cómo presentan los recursos de la API de google:
Página html lanzada directa desde el explorador de windows (**mapa funciona**)
![image](https://user-images.githubusercontent.com/19765542/34802484-a1eca072-f64c-11e7-9efa-ac62a2d45ee7.png)
Todo la API (?) está en "embemed"
![image](https://user-images.githubusercontent.com/19765542/34802496-b87ef402-f64c-11e7-9a3e-b12b0b43164b.png)

Páina html lanzada desde el visual y mostrada desde localhost (**mapa no funciona**)
![image](https://user-images.githubusercontent.com/19765542/34802519-d56bdb7a-f64c-11e7-9f1e-6126cfb6762b.png)
Le faltan archivos a esta última.

**Comment by Alpeh-Jav** [comment]
Ya. Ésto es muy raro.
**Arreglé el problema induciendo un error.** Relee la oración anterior hasta que te quede claro.

Cuando se abrían las páginas utilizando el Explorador de Windows el JavaScript ![image](https://user-images.githubusercontent.com/19765542/34810709-cc9cb79c-f67b-11e7-9bdc-c905f6692dab.png)



creaba la siguiente línea (amarillo) en el html: ![image](https://user-images.githubusercontent.com/19765542/34810639-669c97b4-f67b-11e7-8345-9c83480e7f96.png) pero por un motivo que desconozco le agregaba "file:" (flecha roja)



y eso generaba un error que hacía que no cargara el archivo ![image](https://user-images.githubusercontent.com/19765542/34810825-5c1dbd26-f67c-11e7-966e-8cfdb0b884aa.png) y cuando ese error se daba el google map funcionaba correctamente. LOL.



Ahora resulta que lo único que hice fue agregar un "file:" al javascript para forzar el error y ver si se arreglaba. ![image](https://user-images.githubusercontent.com/19765542/34810876-92e10228-f67c-11e7-9ba1-b0bca326157c.png) y se arregló xDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Alpeh-Jav** [comment]
No. No tengo puta idea de cómo funciona Java Script (relaciones, declaraciones, interconexiones... básicamente cómo se comunica con el html, css, etc.)

**Comment by Alpeh-Jav** [comment]
Como es un fix (? ¿un -fix? ¿un fix inverso? ¿arreglar un problema con otro problema?) pequeño avísame si quieres que lo suba al repo o mejor busco un fix verdadero. Bye. Me voy a dormir.

**Comment by nomad4real** [comment]
Un fix es un fix, si despues se necesita otro fix es otro fix, me cashai?
