### ISSUE TITLE
Imágenes principales del Index no son responsivas

### ISSUE THREAD

**Issue by Alpeh-Jav** [nomad4real/sarrs#6]
![image](https://user-images.githubusercontent.com/19765542/34859745-03e05c3e-f737-11e7-94b2-94aca39d75b3.png)
Ni las imágenes principales en el template html con imágenes (2), ni en el html sin imágenes (3), ni el cshtml del server (4) son responsivas. 
Mientras que en la preview de la template (1) sí los son!
¿Podríamos contactarlos?
![image](https://user-images.githubusercontent.com/19765542/34859810-9fa401f2-f737-11e7-818f-a6a528da3062.png)

**Comment by Alpeh-Jav** [comment]
Revisé las demás, y al menos de las que usamos ninguna más presenta problemas de "responsividad".

**Comment by nomad4real** [comment]
Tal vez sea porque le falta la imagen?

**Comment by Alpeh-Jav** [comment]
En absoluto. Tan tonto no soy xd.

**Comment by nomad4real** [comment]
si no es responsiva para hacerla responsiva. necesitas las imagenes segun el media query. mejor modificar el media query especifici para esa imagen y con algun software para editar imagenes (illustrator) se obtienen dimensiones mas pequeñas

**Comment by nomad4real** [comment]
aaa el preview si servia..sorry me perdi por la la secuencia. que raro wn si sirve en la primera porque no en la otra. le echare una mirada ahota

**Comment by Alpeh-Jav** [comment]
Puta que soy weón, no te conté lo que probé para tratar de arreglarlo. 
Lo que hice fue mirar el código fuente de la preview de la template y comparar linea por linea esa <section></section> con la nuestra. La única diferencia era que en la preview el div de las home-slider-1-slide-2.jpg estaba primero y la de la home-slider-1-slide-1.jpg segundo. Cambié eso en nuestra página y seguía sin ser responsiva. 

Lo segundo que hice fue descargar los js y css de la preview y reemplazar los de nuestro proyecto por ellos, probé tanto con el orden de los div como en la preview como con el orden que teníamos nosotros. Nada funcionó.

**Comment by Alpeh-Jav** [comment]
Se me olvidó. También probé actualizando los nuggets: jquery y bootstrap, y alguno que otro más que no recuerdo. No funcionó.

**Comment by Alpeh-Jav** [comment]
![image](https://user-images.githubusercontent.com/19765542/35364620-e5bc6e88-014e-11e8-8e7b-0a1d6a07faa3.png)
Arreglado. Si no te actualiza el css tienes que limpiar el caché ahí mismo donde te está mostrando la página y luego recargar (+ de media hora perdida para ver porqué no se actualizaba el putos css puto chrome rqlo)
